### ISSUE TITLE
Encounter issue "Invalid MIT-MAGIC-COOKIE-1 key"

### ISSUE THREAD

**Issue by manavmishra96** [nsidn98/NICE#2]
I've encountered an issue while attempting to execute the "test_disrupt.py" code. The error message I'm encountering is "Invalid MIT-MAGIC-COOKIE-1 key." Subsequently, this leads to my terminal becoming unresponsive, requiring a forceful closure of the current terminal window.

Additional Information:

Operating System: Ubuntu 20.04.6 LTS
Python Version: Python 3.8.18
Dependencies/Environment: Install all dependencies on a separate conda environment.

I am using gurobipy version: 9.1.2
<img width="739" alt="new" src="https://github.com/nsidn98/NICE/assets/19229706/6775c082-9a3a-4a78-aa4e-f7df507cf65a">

**Comment by manavmishra96** [comment]
On my Linux system, I'm hitting an "Invalid key" error. But when I give it a shot on macOS terminal using ssh, a different issue pops up: 
![new2](https://github.com/nsidn98/NICE/assets/19229706/3cb90967-fafe-4b05-9200-c2b2f8dba6db)

**Comment by nsidn98** [comment]
Hi, I am not able to replicate the error you have been getting. It seems like it has got to do something with display.

Have you tried any of the solutions posted here:

- [https://askubuntu.com/questions/1238389/invalid-mit-magic-cookie-1-key-message-while-running-a-program-with-the-termin](https://askubuntu.com/questions/1238389/invalid-mit-magic-cookie-1-key-message-while-running-a-program-with-the-termin)
- [https://unix.stackexchange.com/questions/199891/invalid-mit-magic-cookie-1-key-when-trying-to-run-program-remotely](https://unix.stackexchange.com/questions/199891/invalid-mit-magic-cookie-1-key-when-trying-to-run-program-remotely)
- [https://unix.stackexchange.com/questions/85782/error-no-protocol-specified-when-running-from-remote-machine-via-ssh](https://unix.stackexchange.com/questions/85782/error-no-protocol-specified-when-running-from-remote-machine-via-ssh)

**Comment by nsidn98** [comment]
Closing this issue because @manavmishra96 emailed me that it is resolved.
